### ISSUE TITLE
MP assigned to lots of actors

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#10]
Het MP lijkt hier te zijn toegeschreven aan allerlei actoren, diedeels  pas later in artikel staan.

artikel
https://amcat.nl/navigator/projects/1/articlesets/78150/189215519/

naf:
[naf.zip](https://github.com/cltl/micro-portraits/files/3166835/naf.zip)

csv:
[mp_debug4.zip](https://github.com/cltl/micro-portraits/files/3166850/mp_debug4.zip)

**Comment by nruigrok** [comment]
[naf.zip](https://github.com/cltl/micro-portraits/files/3166962/naf.zip)
Nieuwe Naf

**Comment by nruigrok** [comment]
[naf.zip](https://github.com/cltl/micro-portraits/files/3166968/naf.zip)
nog een poging

**Comment by antske** [comment]
Coreference module issue.
