### ISSUE TITLE
Verb as property instead of agent

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#15]
In dit MP is kijken een property ipv een verb. OOk de rest van de zin lijken mij niet alleen properties.

artikel:
https://amcat.nl/navigator/projects/1916/articlesets/78102/193267668/

NAF
[naf.zip](https://github.com/cltl/micro-portraits/files/3169852/naf.zip)

CSV
[debug5.zip](https://github.com/cltl/micro-portraits/files/3169851/debug5.zip)

**Comment by antske** [comment]
Naf used to create this particular file not included.

**Comment by antske** [comment]
Error due to wrong syntactic analysis (square brackets result in `Blok' not being recognized as the subject. Possibly solvable through preprocessing/alternative parser.
