### ISSUE TITLE
output option for "long" format (one word per line)

### ISSUE THREAD

**Issue by vanatteveldt** [cltl/micro-portraits#2]
Current output places multiple words on a line, which can make it difficult to match with information on terms. Would it be possible to make the output in long/tidy/tokenlist/one-word-per-line, giving mention id and role of a word:

portret id | mention id | rol | woord | term_id | woord rol
-- | -- | -- | -- | -- | --
17 | 17.1 | Tijdens-rol | bewindsman | t0 | head
17 | 17.1 | Tijdens-rol | beduusd | t1 | direct modifier
17 | 17.1 | Tijdens-rol | nog | t3 | constituent
17 | 17.1 | Tijdens-rol | van | t4 | constituent
17 | 17.1 | Tijdens-rol | dag | t5 | constituent

**Comment by antske** [comment]
Now standard output of microportraits.
