### ISSUE TITLE
Heeft gezegd dat dubbel in MP

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#6]
Dat heeft minister Blok gezegd in het radioprogramma Nieuws en Co op NPO Radio 1
issue van maken dat hij voltooid deelwoord versie maakt en de hebben + vd versie
Bovendien lijkt het zo te zijn dat bij de versie waar het zeggen is geworden (ipv heeft gezegd) het hd/obj1 voor DAT wel goed wordt aangegeven. In de versie heeft gezegd is dat een constituent geworden. 
Zie voor artikel
https://amcat.nl/navigator/projects/1/articlesets/77805/191539176/

Naf:
[naf.zip](https://github.com/cltl/micro-portraits/files/3161966/naf.zip)
Bestand:
[mp_debug.zip](https://github.com/cltl/micro-portraits/files/3161982/mp_debug.zip)

**Comment by antske** [comment]
Fixed: raising is only taken up once. For coordination and control structures we take all `activities'. If something is a modifier and has a grammatical relation, we remove the modifier (subordinates are already linked to what they modify through coreference).
