### ISSUE TITLE
Dubbel in microportret

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#7]
HEt lijkt erop dat er heel veel dubbel is in dit microportret.
Zie csv
[mp_debug2.zip](https://github.com/cltl/micro-portraits/files/3163004/mp_debug2.zip)
en NAF
[naf.zip](https://github.com/cltl/micro-portraits/files/3163008/naf.zip)
en artikel:
https://amcat.nl/navigator/projects/1/articlesets/78150/190005994/

**Comment by antske** [comment]
Een herhaling is een 'raising constructie' en zou opgelost moeten zijn (NAF en mp kwamen niet overeen in ticket, waardoor ik dit niet kan verifiëren). De andere herhalingen zijn met name onderdelen van de constituenten: als dat genegeerd wordt, vallen ze weg.
