### ISSUE TITLE
MP toegeschreven aan foute actor

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#8]
Hier krijgt de vluchteling wel heel groot MP terwjil het om Blok zou moeten gaan.
Waarschijnlijk vanwege complexiteit.
naf:
[naf.zip](https://github.com/cltl/micro-portraits/files/3163146/naf.zip)
csv:
[mp_debug3.zip](https://github.com/cltl/micro-portraits/files/3163155/mp_debug3.zip)

artikel:
https://amcat.nl/navigator/projects/1916/articlesets/78285/193564609/

**Comment by antske** [comment]
Most likely solved (bug added all words in span of corefering expression as coreferents rather than just the head). Not checked for this particular case, because mp/NAF mismatch
